language: java
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1024m"
script:
  mvn -q clean install
  mvn test
jdk:
  - oraclejdk8

services:
  - mysql

# whitelist
branches:
  only:
    - master
env:
  global:
    database_username: travis
    database_password: ''

before_script:
  - mysql < ./database/databaseCreationScript.sql
